os:
  - osx
dist: trusty
language: node_js
node_js:
  - "12"
install:
  - npm install -g codecov
  - npm install
script:
  - npm run ci
  - codecov
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: coverage/lcov-report
  github-token: $GITHUB_TOKEN
  on: 
    branch: main